<?php

namespace AppBundle\Entity;

/**
 * estado_reservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class estado_reservaRepository extends \Doctrine\ORM\EntityRepository
{
}
